
export const BOOKING_URL = "https://www.booking.com/hotel/za/house-on-plein.en-gb.html?aid=2127702&label=metagha-link-MRZA-hotel-1499572_dev-desktop_los-1_bw-8_dow-Wednesday_defdate-1_room-0_gstadt-2_rateid-public_aud-0_gacid-_mcid-10_ppa-0_clrid-0_ad-0_gstkid-0_checkin-20260408_ppt-&sid=b7d49ca9e2d90abdf4f85f2fdae8d3bc";

export const IMAGES = {
  heroExterior: "https://cf.bstatic.com/xdata/images/hotel/max1024x768/96121313.jpg?k=56a46dbfc1e27e43d5d4e0c7f453b3b99db9cb84f468f368e94171a3d7468ab9&o=",
  garden: "https://cf.bstatic.com/xdata/images/hotel/max1024x768/82950801.jpg?k=ac3545643ae2eebda6bf280ec72a300e83246c1e4cb160465b694bd6cb7a2d3a&o=",
  deluxeRoom: "https://cf.bstatic.com/xdata/images/hotel/max1024x768/137640414.jpg?k=a1f01cc95be5f5e8c4491a82b147fbd7a54aaee02ab998b884edd8ef45259284&o=",
  twinRoom: "https://cf.bstatic.com/xdata/images/hotel/max1024x768/121597583.jpg?k=24bda86aca8a2e3c820463f602e7f2f2cb7a60255fd15c809d9629ff14ec1657&o=",
  cottageRoom: "https://cf.bstatic.com/xdata/images/hotel/max1024x768/137640414.jpg?k=a1f01cc95be5f5e8c4491a82b147fbd7a54aaee02ab998b884edd8ef45259284&o=",
  winelands: "https://cf.bstatic.com/xdata/images/hotel/max1024x768/92454983.jpg?k=5e13b28f748ee58aaaa781ea40da1128949cdd704b92cac9fb6ecfbb2cf8315f&o=",
  bathroom: "https://cf.bstatic.com/xdata/images/hotel/max1024x768/82951618.jpg?k=5c71cae85aef6ff9253240e89047d7973258a722170b562bd56b2eedd9f7bb8f&o=",
  kitchen: "https://cf.bstatic.com/xdata/images/hotel/max1024x768/219825079.jpg?k=b39affe83fbb58cd8947d18341fd8deb5bd4eca430151b162620b73e4efff460&o=",
  victorianInterior: "https://cf.bstatic.com/xdata/images/hotel/max1024x768/137645255.jpg?k=237700373a54ac631bdf364fdc421e491982dbc0d3b2e3f300d9ce731b7f60a3&o=",
  familyRoom: "https://cf.bstatic.com/xdata/images/hotel/max1024x768/92456440.jpg?k=1abecd2d60c2c3312b5f74080f7c4b9d6ade9dbae9485efc6e7e1bac3adb6f8d&o=",
  languageMonument: "https://cf.bstatic.com/xdata/images/hotel/max1024x768/137645725.jpg?k=6bb2742a467330466a0f59ac5ebc96c0f482f9c5614b03740149d217878f207f&o=",
  wineEstate: "https://cf.bstatic.com/xdata/images/hotel/max1024x768/92454983.jpg?k=5e13b28f748ee58aaaa781ea40da1128949cdd704b92cac9fb6ecfbb2cf8315f&o=",
};

export const ROOMS = [
  {
    id: "standard-twin",
    name: "Standard Twin Room",
    subtitle: "with Shared Bathroom",
    beds: "2 single beds",
    size: "25 m²",
    price: "ZAR 649",
    bathroom: "Shared",
    views: [],
    image: "twinRoom",
    amenities: ["Free WiFi", "Towels", "Linen", "Desk", "Seating Area", "Iron", "Fan", "Electric Kettle", "Wardrobe", "Dining Area", "Outdoor Furniture"],
    description: "A comfortable twin room with shared bathroom facilities, featuring two single beds, a desk, seating area, and all essential amenities for a pleasant stay in this historic Victorian home.",
    maxGuests: 2,
  },
  {
    id: "economy-triple",
    name: "Economy Triple Room",
    subtitle: "with Shared Bathroom",
    beds: "3 single beds",
    size: "25 m²",
    price: "ZAR 649",
    bathroom: "Shared",
    views: ["Garden view", "Mountain view", "Landmark view", "City view"],
    image: "familyRoom",
    amenities: ["Free WiFi", "Patio", "Terrace", "Towels", "Linen", "Desk", "Seating Area", "Iron", "Fan", "Electric Kettle", "Wardrobe"],
    description: "Spacious economy room with three single beds and access to shared bathroom. Enjoy beautiful garden and mountain views from your patio and terrace.",
    maxGuests: 3,
  },
  {
    id: "deluxe-queen-mountain",
    name: "Deluxe Queen Room",
    subtitle: "with Mountain View",
    beds: "1 double bed",
    size: "25 m²",
    price: "ZAR 749",
    bathroom: "Ensuite",
    views: ["Garden view", "Mountain view", "Landmark view", "Inner courtyard view"],
    image: "deluxeRoom",
    amenities: ["Free WiFi", "Ensuite Bathroom", "Towels", "Linen", "Desk", "Seating Area", "Iron", "Fan", "Electric Kettle", "Wardrobe"],
    description: "Elegant deluxe room with a comfortable double bed and ensuite bathroom. Wake up to stunning mountain views and enjoy the peaceful inner courtyard.",
    maxGuests: 2,
  },
  {
    id: "deluxe-queen-private",
    name: "Deluxe Queen Room",
    subtitle: "with Private Bathroom",
    beds: "1 large double bed",
    size: "25 m²",
    price: "ZAR 749",
    bathroom: "Ensuite",
    views: ["Garden view", "Mountain view", "Landmark view", "City view"],
    image: "deluxeRoom",
    amenities: ["Free WiFi", "Ensuite Bathroom", "Towels", "Linen", "Desk", "Seating Area", "Iron", "Fan", "Electric Kettle", "Wardrobe"],
    description: "Luxurious deluxe room featuring a large double bed with private ensuite bathroom. Enjoy garden and mountain views in complete privacy and comfort.",
    maxGuests: 2,
  },
  {
    id: "economy-quadruple",
    name: "Economy Quadruple Room",
    subtitle: "with Shared Bathroom",
    beds: "4 single beds",
    size: "35 m²",
    price: "ZAR 649",
    bathroom: "Shared",
    views: [],
    image: "familyRoom",
    amenities: ["Free WiFi", "Towels", "Linen", "Desk", "Seating Area", "Iron", "Fan", "Electric Kettle", "Wardrobe"],
    description: "Generously sized room with four single beds, perfect for families or groups. Shared bathroom facilities with all essential amenities provided.",
    maxGuests: 4,
  },
  {
    id: "king-mountain",
    name: "King Room",
    subtitle: "with Mountain View",
    beds: "2 single beds & 1 double bed",
    size: "35 m²",
    price: "ZAR 749",
    bathroom: "Private",
    views: ["Garden view", "Mountain view", "Landmark view", "City view"],
    image: "deluxeRoom",
    amenities: ["Free WiFi", "Patio", "Terrace", "Private Bathroom", "Towels", "Linen", "Desk", "Seating Area", "Iron", "Fan", "Electric Kettle", "Wardrobe"],
    description: "Spacious king room with a mix of bed types including two singles and a double, private bathroom, and a patio with breathtaking mountain and city views.",
    maxGuests: 4,
  },
  {
    id: "deluxe-double-twin",
    name: "Deluxe Double or Twin Room",
    subtitle: "with Mountain View",
    beds: "1 double bed",
    size: "25 m²",
    price: "ZAR 749",
    bathroom: "Ensuite",
    views: ["Garden view", "Mountain view", "Landmark view", "Inner courtyard view"],
    image: "twinRoom",
    amenities: ["Free WiFi", "Ensuite Bathroom", "Towels", "Linen", "Desk", "Seating Area", "Iron", "Fan", "Electric Kettle", "Wardrobe"],
    description: "Versatile deluxe room that can be configured as a double or twin, with ensuite bathroom. Enjoy mountain views and the tranquil inner courtyard.",
    maxGuests: 2,
  },
  {
    id: "one-bedroom-cottage",
    name: "One-Bedroom Cottage",
    subtitle: "",
    beds: "2 single beds",
    size: "25 m²",
    price: "ZAR 749",
    bathroom: "Private",
    views: ["Garden view", "Mountain view", "Landmark view", "Inner courtyard view"],
    image: "cottageRoom",
    amenities: ["Free WiFi", "Patio", "Terrace", "Private Bathroom", "Towels", "Linen", "Desk", "Seating Area", "Iron", "Fan", "Electric Kettle", "Wardrobe"],
    description: "A charming standalone cottage offering complete privacy with its own patio and terrace. Enjoy garden and mountain views from your private retreat.",
    maxGuests: 2,
  },
  {
    id: "triple-private",
    name: "Triple Room",
    subtitle: "with Private Bathroom",
    beds: "1 single bed & 1 large double bed",
    size: "30 m²",
    price: "ZAR 749",
    bathroom: "Private",
    views: ["Garden view", "Mountain view", "Landmark view", "Inner courtyard view"],
    image: "familyRoom",
    amenities: ["Free WiFi", "Private Bathroom", "Towels", "Linen", "Desk", "Seating Area", "Iron", "Fan", "Electric Kettle", "Wardrobe"],
    description: "Comfortable triple room with a single bed and large double bed, featuring a private bathroom. Perfect for small families or groups wanting more privacy.",
    maxGuests: 3,
  },
];

export const TESTIMONIALS = [
  {
    name: "Sarah M.",
    location: "Cape Town",
    text: "What a charming place! The historic character of the house combined with modern comforts made our stay truly memorable. The garden is an absolute oasis.",
    rating: 5,
  },
  {
    name: "James & Linda K.",
    location: "Johannesburg",
    text: "Perfectly located for exploring the Paarl wine route. We loved the BBQ area and the mountain views from the garden. A real gem!",
    rating: 5,
  },
  {
    name: "Michael T.",
    location: "London, UK",
    text: "The Victorian charm of this 1833 guesthouse is something special. Walking distance to restaurants and wine estates. Will definitely return.",
    rating: 4,
  },
];